-- Seed data intentionally lives in migrations so local resets and remote pushes
-- produce the same salon catalog. The original fake demo seed was removed after
-- replacing it with real Bishkek salon listings.
